# Generated by Django 5.1.2 on 2025-10-28 00:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_alt', models.CharField(blank=True, max_length=30, null=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=100, null=True)),
                ('address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fee_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('PAID', 'Paga'), ('LATE', 'Atrasada'), ('CANCELED', 'Cancelada')], default='OPEN', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('BOLETO', 'Boleto'), ('CARD', 'Cartão'), ('OTHER', 'Outro')], max_length=10, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pix_txid', models.CharField(blank=True, max_length=80, null=True)),
                ('pix_qrcode', models.TextField(blank=True, null=True)),
                ('boleto_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='associados.member')),
            ],
            options={
                'ordering': ('-due_date', 'member__full_name'),
                'indexes': [models.Index(fields=['member', 'due_date'], name='associados__member__525639_idx')],
            },
        ),
    ]
