name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Run Django checks
        env:
          SECRET_KEY: test-secret
          DEBUG: "0"
        run: python backend/manage.py check

      - name: Run tests
        env:
          SECRET_KEY: test-secret
          DEBUG: "0"
        run: pytest
